In [38]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


## Importing library

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

## Loading Datasets from gdrive

In [2]:
# df = pd.read_csv("/content/gdrive/MyDrive/college_project/data_p1.csv")
df = pd.read_csv("data_p1.csv")

In [3]:
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      James Cameron      CCH Pounder  Joel David Moore             Wes Studi   
1     Gore Verbinski      Johnny Depp     Orlando Bloom        Jack Davenport   
2         Sam Mendes  Christoph Waltz      Rory Kinnear      Stephanie Sigman   
3  Christopher Nolan        Tom Hardy    Christian Bale  Joseph Gordon Levitt   
4        Doug Walker      Doug Walker        Rob Walker                   NaN   

                                      genres  \
0  Action Adventure Fantasy science friction   
1                   Action Adventure Fantasy   
2                  Action Adventure Thriller   
3                            Action Thriller   
4                                Documentary   

                                         movie_title  
0                                            Avatar   
1          Pirates of the Caribbean: At World's End   
2                                           Spectre   
3                             The Dark Knight Rises   
4  Star Wars: Episode VII - The Force Awakens    ...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   director_name  4939 non-null   object
 1   actor_1_name   5036 non-null   object
 2   actor_2_name   5030 non-null   object
 3   actor_3_name   5020 non-null   object
 4   genres         5043 non-null   object
 5   movie_title    5043 non-null   object
dtypes: object(6)
memory usage: 236.5+ KB


## Checking NAN value

In [5]:
df.isna().any()

director_name     True
actor_1_name      True
actor_2_name      True
actor_3_name      True
genres           False
movie_title      False
dtype: bool

## Drop NAN value

In [6]:
df = df.dropna()

In [7]:
df.isna().any()

director_name    False
actor_1_name     False
actor_2_name     False
actor_3_name     False
genres           False
movie_title      False
dtype: bool

In [8]:
df.shape

(4919, 6)

In [9]:
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      James Cameron      CCH Pounder  Joel David Moore             Wes Studi   
1     Gore Verbinski      Johnny Depp     Orlando Bloom        Jack Davenport   
2         Sam Mendes  Christoph Waltz      Rory Kinnear      Stephanie Sigman   
3  Christopher Nolan        Tom Hardy    Christian Bale  Joseph Gordon Levitt   
5     Andrew Stanton     Daryl Sabara   Samantha Morton          Polly Walker   

                                      genres  \
0  Action Adventure Fantasy science friction   
1                   Action Adventure Fantasy   
2                  Action Adventure Thriller   
3                            Action Thriller   
5          Action Adventure science friction   

                                 movie_title  
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
5                               John Carter

In [10]:
df['director_name'] = df['director_name'].str.lower()
df['actor_1_name'] = df['actor_1_name'].str.lower()
df['actor_2_name'] = df['actor_2_name'].str.lower()
df['actor_3_name'] = df['actor_3_name'].str.lower()
df['genres'] = df['genres'].str.lower()
df['movie_title'] = df['movie_title'].str.lower()

In [11]:
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      james cameron      cch pounder  joel david moore             wes studi   
1     gore verbinski      johnny depp     orlando bloom        jack davenport   
2         sam mendes  christoph waltz      rory kinnear      stephanie sigman   
3  christopher nolan        tom hardy    christian bale  joseph gordon levitt   
5     andrew stanton     daryl sabara   samantha morton          polly walker   

                                      genres  \
0  action adventure fantasy science friction   
1                   action adventure fantasy   
2                  action adventure thriller   
3                            action thriller   
5          action adventure science friction   

                                 movie_title  
0                                    avatar   
1  pirates of the caribbean: at world's end   
2                                   spectre   
3                     the dark knight rises   
5                               john carter

In [12]:
index = []
for i in range(0 , df.shape[0]):
  index.append(i)

In [13]:
df["index"] = index

In [14]:
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      james cameron      cch pounder  joel david moore             wes studi   
1     gore verbinski      johnny depp     orlando bloom        jack davenport   
2         sam mendes  christoph waltz      rory kinnear      stephanie sigman   
3  christopher nolan        tom hardy    christian bale  joseph gordon levitt   
5     andrew stanton     daryl sabara   samantha morton          polly walker   

                                      genres  \
0  action adventure fantasy science friction   
1                   action adventure fantasy   
2                  action adventure thriller   
3                            action thriller   
5          action adventure science friction   

                                 movie_title  index  
0                                    avatar       0  
1  pirates of the caribbean: at world's end       1  
2                                   spectre       2  
3                     the dark knight rises       3  
5                               john carter       4

In [15]:
df['director_name'] = df['director_name'].str.replace('\d+', '')
df['actor_1_name'] = df['actor_1_name'].str.replace('\d+', '')
df['actor_2_name'] = df['actor_2_name'].str.replace('\d+', '')
df['actor_3_name'] = df['actor_3_name'].str.replace('\d+', '')
df['genres'] = df['genres'].str.replace('\d+', '')
df['movie_title'] = df['movie_title'].str.replace('\d+', '')

<ipython-input-15-5876ff70f3b1>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['director_name'] = df['director_name'].str.replace('\d+', '')
<ipython-input-15-5876ff70f3b1>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['actor_1_name'] = df['actor_1_name'].str.replace('\d+', '')
<ipython-input-15-5876ff70f3b1>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df['actor_2_name'] = df['actor_2_name'].str.replace('\d+', '')
<ipython-input-15-5876ff70f3b1>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['actor_3_name'] = df['actor_3_name'].str.replace('\d+', '')
<ipython-input-15-5876ff70f3b1>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df['genres'] = df['genres'].str.replace('\d+', '')
<ipython-input-15-5876ff70f3b1>:6: Futur

In [16]:
def combined_features(row):
    return row['director_name']+" "+row['actor_1_name']+" "+row['actor_2_name']+" "+row['actor_3_name']+" "+row["genres"]+" "+row["movie_title"]
df["combined_features"] = df.apply(combined_features, axis =1)

In [17]:
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      james cameron      cch pounder  joel david moore             wes studi   
1     gore verbinski      johnny depp     orlando bloom        jack davenport   
2         sam mendes  christoph waltz      rory kinnear      stephanie sigman   
3  christopher nolan        tom hardy    christian bale  joseph gordon levitt   
5     andrew stanton     daryl sabara   samantha morton          polly walker   

                                      genres  \
0  action adventure fantasy science friction   
1                   action adventure fantasy   
2                  action adventure thriller   
3                            action thriller   
5          action adventure science friction   

                                 movie_title  index  \
0                                    avatar       0   
1  pirates of the caribbean: at world's end       1   
2                                   spectre       2   
3                     the dark knight rises       3   
5                               john carter       4   

                                   combined_features  
0  james cameron cch pounder joel david moore wes...  
1  gore verbinski johnny depp orlando bloom jack ...  
2  sam mendes christoph waltz rory kinnear stepha...  
3  christopher nolan tom hardy christian bale jos...  
5  andrew stanton daryl sabara samantha morton po...

## Apply countVectorizer for canverting text into vector

In [18]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Find cosine Similarity

In [19]:
cosine_sim = cosine_similarity(count_matrix)

In [20]:
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      james cameron      cch pounder  joel david moore             wes studi   
1     gore verbinski      johnny depp     orlando bloom        jack davenport   
2         sam mendes  christoph waltz      rory kinnear      stephanie sigman   
3  christopher nolan        tom hardy    christian bale  joseph gordon levitt   
5     andrew stanton     daryl sabara   samantha morton          polly walker   

                                      genres  \
0  action adventure fantasy science friction   
1                   action adventure fantasy   
2                  action adventure thriller   
3                            action thriller   
5          action adventure science friction   

                                 movie_title  index  \
0                                    avatar       0   
1  pirates of the caribbean: at world's end       1   
2                                   spectre       2   
3                     the dark knight rises       3   
5                               john carter       4   

                                   combined_features  
0  james cameron cch pounder joel david moore wes...  
1  gore verbinski johnny depp orlando bloom jack ...  
2  sam mendes christoph waltz rory kinnear stepha...  
3  christopher nolan tom hardy christian bale jos...  
5  andrew stanton daryl sabara samantha morton po...

In [21]:
df['movie_title'] = df['movie_title'].str.strip()
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      james cameron      cch pounder  joel david moore             wes studi   
1     gore verbinski      johnny depp     orlando bloom        jack davenport   
2         sam mendes  christoph waltz      rory kinnear      stephanie sigman   
3  christopher nolan        tom hardy    christian bale  joseph gordon levitt   
5     andrew stanton     daryl sabara   samantha morton          polly walker   

                                      genres  \
0  action adventure fantasy science friction   
1                   action adventure fantasy   
2                  action adventure thriller   
3                            action thriller   
5          action adventure science friction   

                                movie_title  index  \
0                                    avatar      0   
1  pirates of the caribbean: at world's end      1   
2                                   spectre      2   
3                     the dark knight rises      3   
5                               john carter      4   

                                   combined_features  
0  james cameron cch pounder joel david moore wes...  
1  gore verbinski johnny depp orlando bloom jack ...  
2  sam mendes christoph waltz rory kinnear stepha...  
3  christopher nolan tom hardy christian bale jos...  
5  andrew stanton daryl sabara samantha morton po...

Finding the index of the movie

In [32]:
movie_user_likes = "aliens"

def get_index_from_title(title):
    return df[df['movie_title'] == title]["index"].values[0]

movie_index = get_index_from_title(movie_user_likes)

In [33]:
movie_index

2435

In [34]:
similar_movies = list(enumerate(cosine_sim[movie_index]))

In [35]:
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

## Similar Movies

In [36]:
def get_title_from_index(index):
    return df[df.index == index]["movie_title"].values[0]
i=0
for movie in sorted_similar_movies:
    print(get_title_from_index(movie[0]))
    i=i+1
    if i>15:
        break

steve jobs
the last temptation of christ
minority report
avp: alien vs. predator
avatar
lucky number slevin
pearl harbor
rush hour
coco before chanel
the amazing spider-man
the chronicles of narnia: the lion, the witch and the wardrobe
ghostbusters
mars attacks!
universal soldier: the return
nancy drew
the last station


In [37]:
df.to_csv('data.csv')

In [38]:
df[df['movie_title'] == 'aliens']["index"].values[0]

2435

In [27]:
import pickle

In [30]:
Pkl_Filename = "recommendation.pkl"

In [ ]:
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(cosine_sim, file)